@extends('layouts.app')
@section('title','Overview — Tesla Markets')
@section('content')
@php($invested=(float)$user->investments->where('status','active')->sum('balance')) @php($tier=$invested>=25000?'Model X':($invested>=5000?'Model Y':($invested>=500?'Model 3':'Explorer'))) @php($next=$invested<500?500:($invested<5000?5000:($invested<25000?25000:null))) @php($rewardProgress=min(100,$approvedDeposits/1000000*100))
<div class="page-head"><div><span class="eyebrow">PORTFOLIO COMMAND CENTER</span><h1>Good {{ now()->hour<12?'morning':'afternoon' }}, {{ Str::before($user->name,' ') }}.</h1><p>Track cash, packages, positions, and milestones in one view.</p></div><a class="button" href="{{ route('trade.index') }}">Open trading terminal →</a></div>
<section class="stats dashboard-stats">
 <article class="glass stat-card"><div class="stat-top"><i>◫</i><span>BALANCE</span><em>AVAILABLE</em></div><b>${{ number_format($user->cash_balance,2) }}</b><div class="stat-detail"><span>BUYING POWER</span><strong>100%</strong></div><small>Available to trade</small></article>
 <article class="glass stat-card"><div class="stat-top"><i>⌁</i><span>TESLA PACKAGES</span><em>{{ $user->investments->count() }} ACTIVE</em></div><b>${{ number_format($invested,2) }}</b><div class="stat-detail"><span>MODELED ALLOCATION</span><strong>{{ $user->investments->count() }} packages</strong></div><small>Modeled portfolio value</small></article>
 <article class="glass stat-card eligibility-card"><div class="stat-top"><i>↗</i><span>TRADING ELIGIBILITY</span><em>LIVE</em></div><b>{{ $tier }}</b><div class="mini-car"><img class="car-dark" src="{{ asset('images/packages/model-y.png') }}" alt=""><img class="car-light" src="{{ asset('images/packages/model-y-light.png') }}" alt=""></div>@if($next)<small>${{ number_format($next-$invested,2) }} to next tier</small>@else<small>All tiers unlocked</small>@endif</article>
</section>
<section class="reward-target glass cybertruck-target"><picture><source media="(prefers-color-scheme:light)" srcset="{{ asset('images/packages/cybertruck-light.png') }}"><img class="reward-cybertruck" src="{{ asset('images/packages/cybertruck.png') }}" alt="Tesla Cybertruck milestone"></picture><div class="reward-copy"><span class="eyebrow">TESLA REWARD MILESTONE · platform PROMOTION</span><h2>Your road to $1,000,000.</h2><p>Approved platform deposits advance this demonstration milestone. Reaching it shows promotional eligibility only; it does not guarantee a vehicle or prize.</p><a href="{{ route('terms') }}">Read promotion terms →</a></div><div class="reward-visual"><div class="reward-ring" style="--progress:{{ $rewardProgress*3.6 }}deg"><div><b>{{ number_format($rewardProgress,1) }}%</b><span>COMPLETE</span></div></div><div><b>${{ number_format($approvedDeposits,2) }}</b><span>of $1,000,000 approved deposits</span><small>${{ number_format(max(0,1000000-$approvedDeposits),2) }} remaining</small></div></div></section>
<div class="split dashboard-lower"><section class="panel glass"><div class="panel-title"><div><span class="eyebrow">PORTFOLIO</span><h2>Open positions</h2></div><a href="{{ route('trade.index') }}">View activity</a></div>@forelse($positions->filter(fn($q)=>$q>0) as $symbol=>$quantity)<div class="row"><b>{{ $symbol }}</b><span>{{ number_format($quantity,4) }} units</span><strong>${{ number_format($quantity*($quotes[$symbol]??0),2) }}</strong></div>@empty<p class="empty">No positions yet. Your first trade will appear here.</p>@endforelse</section><section class="panel glass"><div class="panel-title"><div><span class="eyebrow">MARKET SNAPSHOT</span><h2>Watchlist</h2></div><span>REFERENCE</span></div>@foreach(array_slice($quotes,0,5,true) as $symbol=>$price)<div class="market-mini"><b>{{ $symbol }}</b><canvas data-chart data-series="20,24,22,29,27,34,31,39" data-color="{{ $loop->even?'#69d99b':'#ef3f42' }}"></canvas><strong>${{ number_format($price,2) }}</strong></div>@endforeach</section></div>
@endsection
