@extends('layouts.app')
@section('title','Tesla Markets — trading, reimagined')
@section('content')
<section class="video-story video-hero"><div class="video-bg"><iframe src="https://www.youtube.com/embed/_OiEwIUQzDk?autoplay=1&mute=1&loop=1&playlist=_OiEwIUQzDk&controls=0&modestbranding=1&playsinline=1&rel=0" title="Tesla market story" allow="autoplay; encrypted-media; picture-in-picture" loading="eager"></iframe></div><div class="video-shade"></div><div class="video-copy"><span class="eyebrow">ENGINEERED FOR MOMENTUM</span><h2>Where mobility meets markets.</h2><p>A cinematic look at the design language inspiring this educational trading experience.</p><a class="outline" href="{{ auth()->check()?route('trade.index'):route('register') }}">Start trading →</a></div><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div></section>
<section class="hero trading-hero">
    <img class="hero-dark" src="{{ asset('images/tesla-market-hero.png') }}" alt="White electric vehicle in a dark market studio"><img class="hero-light" src="{{ asset('images/tesla-market-hero-light.png') }}" alt="Black electric vehicle in a light market studio">
    <div class="hero-copy"><span class="eyebrow">MULTI-ASSET trading</span><h1>Markets in<br><em>motion.</em></h1><p>Explore stocks and crypto, test strategies, and learn disciplined risk management without putting real money at stake.</p><div><a class="button" href="{{ route('register') }}">Start with $100k simulated</a><a class="text-link" href="{{ route('login') }}">Open terminal →</a></div></div>
    <div class="hero-chart glass"><div class="chart-top"><div><span>TSLA / USD</span><b>$445.91</b></div><strong>+1.42%</strong></div><canvas class="market-chart" data-chart data-series="410,414,409,419,422,420,431,428,437,434,441,445,443,448,445.91" data-color="#ef3f42"></canvas><div class="chart-times"><span>09:30</span><span>12:00</span><span>16:00</span></div></div>
    <div class="market-strip ticker"><div class="ticker-track"><span>S&amp;P 500 <b>5,932.71</b> <i>+0.41%</i></span><span>NASDAQ <b>19,218.17</b> <i>+0.67%</i></span><span>TSLA <b>$445.91</b> <i>+1.42%</i></span><span>BTC <b>$118,420</b> <i>+2.31%</i></span><span>ETH <b>$4,218</b> <i>+1.76%</i></span><span>SOL <b>$196.42</b> <i>+3.08%</i></span></div></div>
</section>
<section class="market-board"><div class="section-heading"><div><span class="eyebrow">MARKET PULSE</span><h2>One terminal. Two asset classes.</h2></div><a href="{{ route('register') }}">Explore all markets →</a></div><div class="market-cards"><article class="market-card glass"><span>STOCK</span><div><b>TSLA</b><strong>$445.91</strong></div><canvas data-chart data-series="421,418,426,429,425,435,441,438,445" data-color="#69d99b"></canvas><small>+1.42% TODAY</small></article><article class="market-card glass"><span>CRYPTO</span><div><b>BTC</b><strong>$118,420.35</strong></div><canvas data-chart data-series="112400,114800,113900,116200,115700,117300,118900,117800,118420" data-color="#f7931a"></canvas><small>+2.31% TODAY</small></article><article class="market-card glass"><span>CRYPTO</span><div><b>ETH</b><strong>$4,218.67</strong></div><canvas data-chart data-series="3980,4050,4020,4090,4140,4110,4180,4160,4218" data-color="#627eea"></canvas><small>+1.76% TODAY</small></article></div></section>
<section class="features"><article><span>01</span><h3>Stocks + crypto</h3><p>Practice across major equities and digital assets in one simulated portfolio.</p></article><article><span>02</span><h3>Tesla packages</h3><p>Build modeled package eligibility from Model 3 through Model X.</p></article><article><span>03</span><h3>Grok Assistant</h3><p>Get instant product support with an optional, clearly labeled human escalation.</p></article></section>
<section class="landing-detail"><div class="detail-copy"><span class="eyebrow">A COMPLETE MARKET WORKSPACE</span><h2>From first deposit to disciplined portfolio.</h2><p>Every part of the experience is designed to make complex market workflows understandable: simulated funding, compliance review, multi-asset execution, package milestones, and on-demand support.</p><div class="detail-points"><span><b>01</b>Clear order estimates before execution</span><span><b>02</b>Portfolio and eligibility tracking</span><span><b>03</b>Private KYC review workflow</span><span><b>04</b>Transaction monitoring and audit trail</span></div></div><div class="terminal-preview glass"><div><span>PORTFOLIO VALUE</span><b>$128,402.19</b><em>+8.42%</em></div><canvas data-chart data-series="62,66,64,71,69,78,76,84,82,91,96,101" data-color="#ef3f42"></canvas><div class="preview-bars"><i style="height:35%"></i><i style="height:52%"></i><i style="height:44%"></i><i style="height:72%"></i><i style="height:61%"></i><i style="height:88%"></i><i style="height:76%"></i></div></div></section>
<section class="musk-profile glass">
    <figure class="musk-portrait">
        <img src="https://upload.wikimedia.org/wikipedia/commons/e/e1/Elon_Musk_%28cropped%29.jpg" alt="Portrait of Elon Musk" loading="lazy">
        <figcaption>Photo: Debbie Rowe · <a href="https://commons.wikimedia.org/wiki/File:Elon_Musk_(cropped).jpg" rel="noopener noreferrer" target="_blank">Wikimedia Commons, CC BY-SA</a></figcaption>
    </figure>
    <div class="musk-copy"><span class="eyebrow">VISION &amp; INDUSTRY</span><h2>Elon Musk</h2><p class="musk-lead">An entrepreneur whose work has connected electric mobility, reusable rockets, energy systems, artificial intelligence, and infrastructure.</p><p>Musk joined Tesla’s board in 2004 and has served as its chief executive since 2008. He also founded SpaceX and helped build ventures including Neuralink and The Boring Company, following earlier technology businesses Zip2 and PayPal.</p><div class="musk-milestones"><span><b>2002</b>SpaceX founded</span><span><b>2004</b>Joined Tesla’s board</span><span><b>2008</b>Became Tesla CEO</span></div><small>This independent educational simulator is not endorsed by or affiliated with Elon Musk, Tesla, SpaceX, or xAI.</small></div>
</section>
<section class="how-it-works"><div class="section-heading"><div><span class="eyebrow">START IN MINUTES</span><h2>A guided path into markets.</h2></div></div><div class="workflow-grid"><article><i>01</i><h3>Create your account</h3><p>Start with a BALANCE balance and a secure personal dashboard.</p></article><article><i>02</i><h3>Complete verification</h3><p>Experience a compliance-first KYC, sanctions, and monitoring workflow.</p></article><article><i>03</i><h3>Build and trade</h3><p>Explore stocks, crypto, and Tesla-inspired investment packages.</p></article><article><i>04</i><h3>Measure progress</h3><p>Follow positions, eligibility tiers, and disclosed platform milestones.</p></article></div></section>
<section class="team-section"><div class="section-heading"><div><span class="eyebrow">MEET THE TEAM</span><h2>Built across disciplines.</h2></div><p>Product thinking, market infrastructure, safety, and support working as one system.</p></div><div class="team-grid"><article class="team-card glass"><div class="team-avatar">PX</div><span>PRODUCT EXPERIENCE</span><h3>Designing for clarity</h3><p>Turns complex trading workflows into understandable, deliberate decisions.</p><i>01</i></article><article class="team-card glass"><div class="team-avatar">ME</div><span>MARKET ENGINEERING</span><h3>Building the terminal</h3><p>Creates resilient simulated execution, portfolio, and pricing systems.</p><i>02</i></article><article class="team-card glass"><div class="team-avatar">CO</div><span>COMPLIANCE OPERATIONS</span><h3>Protecting the workflow</h3><p>Shapes verification, monitoring, reconciliation, and administrator review.</p><i>03</i></article><article class="team-card glass"><div class="team-avatar">CX</div><span>CUSTOMER EXPERIENCE</span><h3>Supporting every step</h3><p>Connects Grok’s instant guidance with accountable human assistance.</p><i>04</i></article></div></section>
<section class="motion-marquee" aria-hidden="true"><div>TRADE · LEARN · BUILD · VERIFY · MEASURE · <span>MOVE FORWARD</span> · TRADE · LEARN · BUILD · VERIFY ·</div></section>
<section class="landing-cta glass"><div><span class="eyebrow">YOUR NEXT MOVE</span><h2>Build a portfolio for your future.</h2><p>Practice the workflow. Understand the controls. Learn from every simulated decision.</p></div><a class="button" href="{{ route('register') }}">Create free account →</a></section>
@endsection
