<?php
namespace App\Services;
use App\Models\{Conversation,InvestmentPackage,Message,User};
use Illuminate\Support\Facades\Mail;
class AssistantService {
 public function reply(Conversation $conversation,string $input): Message {
  $risk=(float)$conversation->risk_budget;$user=$conversation->user;$text=strtolower(trim($input));$escalate=(bool)preg_match('/\b(human|agent|administrator|admin|customer support|representative|complaint)\b/',$text);
  $packages=InvestmentPackage::catalog();$packageSummary=$packages->map(fn($p)=>"{$p->name}: $".number_format((float)$p->minimum)."–$".number_format((float)$p->maximum)." at ".number_format((float)$p->annual_rate,2)."% modeled annually")->join('; ');
  if(preg_match('/^(hi|hello|hey|good morning|good afternoon|good evening)\b/',$text))$body="Hi ".str($user->name)->before(' ')."—I’m Grok Assistant. I can inspect your current account status and guide you through funding, wire transfers, KYC, packages, searchable markets, closing positions, or daily risk. What would you like to accomplish?";
  elseif(preg_match('/\b(wire|bank transfer|bank account|routing|swift|iban)\b/',$text))$body="Open Funding and select Wire transfer. Company instructions appear with a 20-minute timer because they may change. For a deposit, use the displayed reference and submit your transfer reference afterward. For a withdrawal, provide your receiving bank details. Every request still requires administrator confirmation.";
  elseif(preg_match('/\b(deposit|wallet|fund|add money|crypto transfer)\b/',$text))$body="Your KYC status is {$user->kyc_status} and sanctions status is {$user->sanctions_status}. To deposit, open Funding, choose Crypto or Wire, enter the USD amount, and follow the displayed instructions. Crypto converts from the current reference rate automatically; an administrator confirms the request before your platform balance changes.";
  elseif(preg_match('/\b(withdraw|withdrawal|cash out|take out)\b/',$text))$body="Choose Withdraw under Funding, then select Crypto or Wire. Enter the amount and destination details. The simulated amount is held immediately, screened, and released only after administrator confirmation—or restored if rejected.";
  elseif(preg_match('/\b(kyc|verify|verification|document|identity|passport|license)\b/',$text))$body="Your current KYC status is {$user->kyc_status}. Open Verify, enter your legal name, birth date and country code, then upload a PDF, JPG or PNG under 10 MB. Files stay on private storage and the administrator completes KYC and sanctions review.";
  elseif(preg_match('/\b(package|packages|model 3|model y|model x|cybertruck|invest|profit|return|percentage)\b/',$text))$body="Current packages are {$packageSummary}. The administrator can change these ranges and rates. Your package balance determines trading eligibility, while all profit figures remain modeled platform assumptions—not promised returns.";
  elseif(preg_match('/\b(close|exit|liquidate).*(trade|position)|\bposition.*(close|exit)\b/',$text))$body="Open the Trading Terminal and scroll to Open positions. Select Close position beside the market you want to exit. The full quantity is sold at the current simulated reference price and returned to your platform cash balance.";
  elseif(preg_match('/\b(chart|timeframe|1h|1d|1w|1m|1y|search stock|find stock)\b/',$text))$body="On the Trading Terminal, use the search field to filter symbols or company names. Select any watchlist row, switch between 1H, 1D, 1W, 1M and 1Y, and click or move across the chart to inspect individual reference points.";
  elseif(preg_match('/\b(buy|sell|trade|order|stock|bitcoin|ethereum|crypto|market)\b/',$text))$body="The terminal supports equities and crypto using simulated reference prices. Search or select a market, choose Buy or Sell, enter quantity, review the estimate, and execute. Grok Assistant can explain the workflow but cannot place an order for you.";
  elseif(preg_match('/\b(profile|email|name|change password|password)\b/',$text))$body="Open Profile from the top navigation to change your name, email, or password. Password changes require your current password. Never share credentials or recovery phrases here.";
  elseif($escalate)$body="I’ve escalated this conversation to customer support with the existing context. You can keep this page open—new administrator replies will appear automatically.";
  elseif(preg_match('/\b(risk|loss|budget|position size|stop)\b/',$text)||$risk>0){$budget=$risk>0?$risk:100;$maxPosition=max(1,round($budget*.25,2));$stop=max(1,round($budget*.5,2));$body="Using a simulated daily risk budget of $".number_format($budget,2).", a cautious practice framework would cap one position near $".number_format($maxPosition,2).", pause after roughly $".number_format($stop,2)." of losses, and stop completely at the daily limit. This is educational guidance, not personalized financial advice.";}
  elseif(preg_match('/\b(fee|cost|charge|spread)\b/',$text))$body="This platform currently charges no real fees. Any displayed network fee, spread, yield or execution value is an educational estimate rather than a live-service quote.";
  else $body="I’m not fully certain what you mean yet. I can help with funding, wire instructions, withdrawals, KYC, packages, stock and crypto trading, charts, closing positions, profile settings, fees, and risk controls. Tell me the outcome you want—for example, ‘help me close my TSLA position’—or ask for customer support.";
  $message=$conversation->messages()->create(['author_type'=>'assistant','body'=>$body]);
  $conversation->update(['status'=>$escalate?'escalated':'automated']);
  if($escalate){$admin=User::where('is_admin',true)->first();if($admin){try{Mail::raw("Conversation #{$conversation->id} needs a human response.\n\nUser: {$input}",fn($mail)=>$mail->to($admin->email)->subject('Tesla Markets support escalation'));}catch(\Throwable $e){report($e);}}}
  return $message;
 }
}
