import './bootstrap';
import QRCode from 'qrcode';
const themeButton=document.querySelector('.theme');
const syncTheme=()=>{if(themeButton)themeButton.textContent=document.documentElement.classList.contains('light')?'☾':'☼'};
themeButton?.addEventListener('click',()=>{document.documentElement.classList.toggle('light');localStorage.theme=document.documentElement.classList.contains('light')?'light':'dark';syncTheme()});syncTheme();
const menuToggle=document.querySelector('.menu-toggle'),mobileNav=menuToggle?document.getElementById(menuToggle.getAttribute('aria-controls')):null;
if(menuToggle&&mobileNav){const closeMenu=()=>{document.body.classList.remove('menu-open');menuToggle.setAttribute('aria-expanded','false');menuToggle.setAttribute('aria-label','Open navigation')},openMenu=()=>{document.body.classList.add('menu-open');menuToggle.setAttribute('aria-expanded','true');menuToggle.setAttribute('aria-label','Close navigation')};menuToggle.addEventListener('click',e=>{e.stopPropagation();document.body.classList.contains('menu-open')?closeMenu():openMenu()});mobileNav.addEventListener('click',e=>{e.stopPropagation();if(e.target.closest('a'))closeMenu()});document.addEventListener('click',e=>{if(document.body.classList.contains('menu-open')&&!mobileNav.contains(e.target)&&!menuToggle.contains(e.target))closeMenu()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});window.addEventListener('resize',()=>{if(window.innerWidth>850)closeMenu()})}
const fundingType=document.querySelector('#fundingType'),destination=document.querySelector('#destinationField');
const syncFunding=()=>{if(destination)destination.hidden=fundingType?.value!=='withdrawal'};fundingType?.addEventListener('change',syncFunding);syncFunding();

const fundingShell=document.querySelector('[data-funding]');
if(fundingShell){
 const tabs=[...fundingShell.querySelectorAll('[data-funding-tab]')],assets=[...fundingShell.querySelectorAll('[data-asset]')];
 const typeInput=fundingShell.querySelector('[data-funding-type]'),assetInput=fundingShell.querySelector('[data-funding-asset]'),networkInput=fundingShell.querySelector('[data-funding-network]');
 const depositPanel=fundingShell.querySelector('[data-deposit-panel]'),destinationField=fundingShell.querySelector('.destination-field'),submitButton=fundingShell.querySelector('.submit-row .button'),canvas=fundingShell.querySelector('[data-wallet-qr]'),usdAmount=fundingShell.querySelector('[data-usd-amount]'),cryptoAmount=fundingShell.querySelector('[data-crypto-amount]');
 const methodButtons=[...fundingShell.querySelectorAll('[data-payment-method]')],methodInput=fundingShell.querySelector('[data-payment-input]'),cryptoPanel=fundingShell.querySelector('[data-crypto-panel]'),wirePanel=fundingShell.querySelector('[data-wire-panel]'),wireWithdrawal=fundingShell.querySelector('[data-wire-withdrawal]'),rateLine=fundingShell.querySelector('[data-rate-line]'),cryptoAmountField=fundingShell.querySelector('[data-crypto-amount-field]');
 let current=assets[0];
 const convertAmount=()=>{if(methodInput.value==='wire'){cryptoAmount.value=usdAmount.value||'';return}const rate=Number(current?.dataset.rate)||1;cryptoAmount.value=usdAmount.value?((Number(usdAmount.value)||0)/rate).toFixed(current.dataset.asset.startsWith('USD')?2:8):'';fundingShell.querySelector('[data-live-rate]').textContent='$'+rate.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});fundingShell.querySelector('[data-rate-asset]').textContent=current.dataset.asset;};
 const renderWallet=()=>{if(!current)return;assets.forEach(a=>a.classList.toggle('active',a===current));assetInput.value=current.dataset.asset;networkInput.value=current.dataset.network;fundingShell.querySelectorAll('[data-wallet-asset]').forEach(el=>el.textContent=current.dataset.asset);fundingShell.querySelectorAll('[data-wallet-network]').forEach(el=>el.textContent=current.dataset.network.toUpperCase());fundingShell.querySelector('[data-wallet-address]').textContent=current.dataset.address;QRCode.toCanvas(canvas,current.dataset.address,{width:152,margin:1,color:{dark:'#080808',light:'#ffffff'}},()=>{});convertAmount();};
 assets.forEach(a=>a.addEventListener('click',()=>{current=a;renderWallet()}));usdAmount?.addEventListener('input',convertAmount);
 const syncDestinationFields=()=>{const withdrawal=typeInput.value==='withdrawal',wire=methodInput.value==='wire';destinationField.hidden=!withdrawal||wire;destinationField.querySelector('input').required=withdrawal&&!wire;wireWithdrawal.hidden=!withdrawal||!wire;wireWithdrawal.querySelectorAll('input').forEach(input=>input.required=withdrawal&&wire&&['beneficiary_name','bank_name','account_number'].includes(input.name));wirePanel.hidden=!wire||withdrawal};
 tabs.forEach(tab=>tab.addEventListener('click',()=>{const type=tab.dataset.fundingTab;tabs.forEach(t=>t.classList.toggle('active',t===tab));typeInput.value=type;depositPanel.hidden=type==='withdrawal'||methodInput.value==='wire';syncDestinationFields();submitButton.textContent=type==='deposit'?'Create deposit ticket →':'Request withdrawal →';fundingShell.querySelector('[data-final-step]').textContent=type==='deposit'?'Enter transfer details':'Enter withdrawal details';}));
 methodButtons.forEach(button=>button.addEventListener('click',()=>{const method=button.dataset.paymentMethod;methodButtons.forEach(b=>b.classList.toggle('active',b===button));methodInput.value=method;cryptoPanel.hidden=method==='wire';depositPanel.hidden=method==='wire'||typeInput.value==='withdrawal';rateLine.hidden=method==='wire';cryptoAmountField.hidden=method==='wire';cryptoAmount.required=method==='crypto';syncDestinationFields();convertAmount()}));
 fundingShell.querySelector('[data-copy-wallet]')?.addEventListener('click',async e=>{await navigator.clipboard.writeText(current.dataset.address);e.currentTarget.querySelector('span').textContent='Address copied';setTimeout(()=>e.currentTarget.querySelector('span').textContent='Copy address',1600)});
 renderWallet();syncDestinationFields();
 fetch('https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,ethereum&vs_currencies=usd').then(r=>r.ok?r.json():Promise.reject()).then(data=>{assets.forEach(a=>{if(a.dataset.asset==='BTC'&&data.bitcoin?.usd)a.dataset.rate=data.bitcoin.usd;if(a.dataset.asset==='ETH'&&data.ethereum?.usd)a.dataset.rate=data.ethereum.usd});fundingShell.querySelector('[data-rate-status]').textContent='LIVE MARKET RATE';renderWallet()}).catch(()=>fundingShell.querySelector('[data-rate-status]').textContent='REFERENCE RATE · OFFLINE');
 const timer=fundingShell.querySelector('[data-wire-timer]');if(timer){const tick=()=>{const left=Math.max(0,Number(timer.dataset.expires)*1000-Date.now()),minutes=Math.floor(left/60000),seconds=Math.floor(left%60000/1000);timer.textContent=left?`${String(minutes).padStart(2,'0')}:${String(seconds).padStart(2,'0')}`:'EXPIRED · REFRESH';timer.classList.toggle('expired',!left)};tick();setInterval(tick,1000)}
}

const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('revealed');revealObserver.unobserve(entry.target)}}),{threshold:.12});
document.querySelectorAll('.car-package,.portfolio-section,.funding-main,.funding-side,.eligibility').forEach(el=>revealObserver.observe(el));

const preloader=document.querySelector('.preloader');
window.addEventListener('load',()=>setTimeout(()=>preloader?.classList.add('loaded'),350));
setTimeout(()=>preloader?.classList.add('loaded'),2200);

const drawLineChart=(canvas,values,color='#ef3f42')=>{
 const ratio=Math.min(window.devicePixelRatio||1,2),rect=canvas.getBoundingClientRect();if(!rect.width||!rect.height)return;
 canvas.width=rect.width*ratio;canvas.height=rect.height*ratio;const ctx=canvas.getContext('2d');ctx.scale(ratio,ratio);const w=rect.width,h=rect.height,p=8,min=Math.min(...values),max=Math.max(...values),range=max-min||1;
 const points=values.map((v,i)=>[p+(i/(values.length-1))*(w-p*2),p+(1-(v-min)/range)*(h-p*2)]);
 const gradient=ctx.createLinearGradient(0,0,0,h);gradient.addColorStop(0,color+'55');gradient.addColorStop(1,color+'00');ctx.beginPath();ctx.moveTo(points[0][0],h);points.forEach(([x,y])=>ctx.lineTo(x,y));ctx.lineTo(points.at(-1)[0],h);ctx.closePath();ctx.fillStyle=gradient;ctx.fill();ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.strokeStyle=color;ctx.lineWidth=2;ctx.shadowColor=color;ctx.shadowBlur=8;ctx.stroke();
};
const renderMiniCharts=()=>document.querySelectorAll('[data-chart]').forEach(c=>drawLineChart(c,c.dataset.series.split(',').map(Number),c.dataset.color));
renderMiniCharts();

const terminal=document.querySelector('[data-terminal]');
if(terminal){
 const histories=JSON.parse(terminal.dataset.histories),chart=terminal.querySelector('[data-trade-chart]'),rows=[...terminal.querySelectorAll('[data-market]')],qty=terminal.querySelector('[data-quantity]'),tooltip=terminal.querySelector('[data-chart-tooltip]');let active=rows[0],timeframe='1D',visibleValues=[];
 const money=n=>'$'+Number(n).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:Number(n)<10?3:2});
 const timeframePoints={"1H":12,"1D":24,"1W":48,"1M":72,"1Y":96};
 const selectMarket=row=>{active=row;rows.forEach(r=>r.classList.toggle('active',r===row));const s=row.dataset.market,p=Number(row.dataset.price);visibleValues=histories[s].slice(-timeframePoints[timeframe]);terminal.querySelector('[data-current-symbol]').textContent=s;terminal.querySelector('[data-current-type]').textContent=row.dataset.type==='crypto'?'CRYPTO · USD':'NASDAQ · EQUITY';terminal.querySelector('[data-current-price]').textContent=money(p);terminal.querySelector('[data-order-symbol]').textContent=s+' / USD';terminal.querySelector('[data-order-input]').value=s;terminal.querySelector('[data-order-price]').textContent=money(p);terminal.querySelector('[data-stat-open]').textContent=money(visibleValues[0]);terminal.querySelector('[data-stat-high]').textContent=money(Math.max(...visibleValues));terminal.querySelector('[data-stat-low]').textContent=money(Math.min(...visibleValues));terminal.querySelector('[data-current-icon] img').src=row.querySelector('img').src;drawLineChart(chart,visibleValues,row.dataset.type==='crypto'?'#f7931a':'#ef3f42');updateTotal();};
 const updateTotal=()=>terminal.querySelector('[data-order-total]').textContent=money((Number(qty.value)||0)*Number(active.dataset.price));
 let watchFilter='all',searchTerm='';const filterRows=()=>{let shown=0;rows.forEach(r=>{const matchType=watchFilter==='all'||r.dataset.type===watchFilter,matchText=(r.dataset.market+' '+r.dataset.name).toLowerCase().includes(searchTerm);r.hidden=!(matchType&&matchText);if(!r.hidden)shown++});terminal.querySelector('[data-search-empty]').hidden=shown>0};
 rows.forEach(r=>r.addEventListener('click',()=>selectMarket(r)));qty.addEventListener('input',updateTotal);terminal.querySelectorAll('[data-watch]').forEach(b=>b.addEventListener('click',()=>{terminal.querySelectorAll('[data-watch]').forEach(x=>x.classList.toggle('active',x===b));watchFilter=b.dataset.watch;filterRows()}));terminal.querySelector('[data-market-search]').addEventListener('input',e=>{searchTerm=e.target.value.trim().toLowerCase();filterRows()});terminal.querySelectorAll('[data-timeframe]').forEach(b=>b.addEventListener('click',()=>{terminal.querySelectorAll('[data-timeframe]').forEach(x=>x.classList.toggle('active',x===b));timeframe=b.dataset.timeframe;selectMarket(active)}));
 const inspectChart=e=>{const rect=chart.getBoundingClientRect(),x=Math.max(0,Math.min(rect.width,e.clientX-rect.left)),index=Math.round((x/rect.width)*(visibleValues.length-1)),value=visibleValues[index];tooltip.hidden=false;tooltip.style.left=Math.min(rect.width-90,Math.max(8,x))+'px';tooltip.style.top=Math.max(8,e.clientY-rect.top-48)+'px';tooltip.querySelector('b').textContent=money(value);tooltip.querySelector('span').textContent=timeframe+' · point '+(index+1)};chart.addEventListener('pointermove',inspectChart);chart.addEventListener('click',inspectChart);chart.addEventListener('pointerleave',()=>tooltip.hidden=true);selectMarket(active);
}

document.querySelectorAll('.quick-prompts button').forEach(button=>button.addEventListener('click',()=>{const input=document.querySelector('.composer textarea');input.value=button.textContent;input.focus()}));
const realtimeChat=document.querySelector('[data-realtime-chat]');
if(realtimeChat){const form=realtimeChat.querySelector('[data-chat-form]'),list=realtimeChat.querySelector('[data-message-list]'),typing=realtimeChat.querySelector('[data-typing]'),status=realtimeChat.querySelector('[data-chat-status]');let lastId=Number(list.dataset.lastId)||0,busy=false;const addMessage=m=>{if(list.querySelector(`[data-message-id="${m.id}"]`))return;const el=document.createElement('div');el.className='message '+(m.author_type==='user'?'user':'assistant');el.dataset.messageId=m.id;const small=document.createElement('small'),p=document.createElement('p');small.textContent=m.label;p.textContent=m.body;el.append(small,p);list.append(el);const numericId=Number(m.id);if(Number.isFinite(numericId)){lastId=Math.max(lastId,numericId);list.dataset.lastId=lastId}list.scrollTo({top:list.scrollHeight,behavior:'smooth'})};form.addEventListener('submit',async e=>{e.preventDefault();if(busy)return;busy=true;typing.hidden=false;const button=form.querySelector('button');button.disabled=true;try{const response=await fetch(form.action,{method:'POST',headers:{'Accept':'application/json','X-CSRF-TOKEN':form.querySelector('[name="_token"]').value},body:new FormData(form)});const data=await response.json();if(!response.ok)throw new Error(data.message||'Message could not be sent.');data.messages.forEach(addMessage);form.querySelector('textarea').value='';}catch(error){const fake={id:'error-'+Date.now(),author_type:'assistant',label:'SYSTEM',body:error.message};addMessage(fake)}finally{typing.hidden=true;button.disabled=false;busy=false}});const poll=async()=>{if(document.hidden)return;try{const response=await fetch(realtimeChat.dataset.pollUrl+'?after='+lastId,{headers:{'Accept':'application/json'}});if(!response.ok)return;const data=await response.json();data.messages.forEach(addMessage);if(data.status)status.textContent=data.status.replaceAll('_',' ')}catch{}};setInterval(poll,2500);list.scrollTop=list.scrollHeight;}
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{renderMiniCharts();if(terminal)terminal.querySelector('[data-market].active')?.click()},150)});
