@extends('layouts.app')
@section('title','Trading Terminal — Tesla Markets')
@section('content')
@php($iconSlugs=['TSLA'=>'tesla','NVDA'=>'nvidia','AAPL'=>'apple','MSFT'=>'microsoft','AMZN'=>'amazon','BTC'=>'bitcoin','ETH'=>'ethereum','SOL'=>'solana','XRP'=>'xrp'])
<div class="terminal-head"><div><span class="eyebrow">TESLA MARKETS TERMINAL</span><h1>Trade markets.</h1></div><div class="market-state"><i></i><span>ONLINE</span><b>DELAYED REFERENCE PRICES</b></div></div>
<div class="terminal-grid" data-terminal data-histories='@json($histories)'>
 <aside class="watchlist glass"><label class="market-search"><span>⌕</span><input type="search" placeholder="Search stocks or crypto" data-market-search></label><div class="watch-tabs"><button class="active" data-watch="all">All</button><button data-watch="stock">Stocks</button><button data-watch="crypto">Crypto</button></div><div class="watch-head"><span>Market</span><span>Price</span><span>24h</span></div>@foreach($quotes as $symbol=>$price)@php($isCrypto=array_key_exists($symbol,$crypto))<button class="watch-row {{ $loop->first?'active':'' }}" data-market="{{ $symbol }}" data-name="{{ ['TSLA'=>'Tesla','NVDA'=>'Nvidia','AAPL'=>'Apple','MSFT'=>'Microsoft','AMZN'=>'Amazon','BTC'=>'Bitcoin','ETH'=>'Ethereum','SOL'=>'Solana','XRP'=>'XRP'][$symbol] }}" data-type="{{ $isCrypto?'crypto':'stock' }}" data-price="{{ $price }}"><span><i class="instrument-icon"><img src="https://cdn.simpleicons.org/{{ $iconSlugs[$symbol] }}/{{ $isCrypto?'ffffff':'ef3f42' }}" alt="{{ $symbol }} logo"></i><b>{{ $symbol }}</b><small>{{ $isCrypto?'CRYPTO · USD':'NASDAQ' }}</small></span><strong>${{ number_format($price,$price<10?3:2) }}</strong><em>+{{ number_format(.6+$loop->index*.31,2) }}%</em></button>@endforeach<div class="watch-empty" data-search-empty hidden>No matching markets</div></aside>
 <section class="chart-terminal glass"><div class="instrument-title"><div><span class="instrument-icon large" data-current-icon><img src="https://cdn.simpleicons.org/tesla/ffffff" alt=""></span><div><h2 data-current-symbol>TSLA</h2><small data-current-type>NASDAQ · EQUITY</small></div></div><div><b data-current-price>$445.91</b><strong>+1.42%</strong></div></div><div class="timeframes"><button data-timeframe="1H">1H</button><button class="active" data-timeframe="1D">1D</button><button data-timeframe="1W">1W</button><button data-timeframe="1M">1M</button><button data-timeframe="1Y">1Y</button></div><div class="chart-stage" data-chart-stage><div class="price-axis"><span>HIGH</span><span>MID</span><span>LOW</span></div><canvas data-trade-chart></canvas><div class="chart-tooltip" data-chart-tooltip hidden><b></b><span></span></div></div><div class="terminal-stats"><span>Open <b data-stat-open>$438.21</b></span><span>High <b data-stat-high>$451.09</b></span><span>Low <b data-stat-low>$429.72</b></span><span>Volume <b>18.42M</b></span></div></section>
 <aside class="order-ticket glass"><div class="ticket-title"><div><span class="eyebrow">ORDER TICKET</span><h2 data-order-symbol>TSLA / USD</h2></div><span class="live-dot">LIVE</span></div><form method="post" action="{{ route('trade.store') }}">@csrf<input type="hidden" name="symbol" value="TSLA" data-order-input><div class="trade-side"><label><input type="radio" name="side" value="buy" checked><span>Buy</span></label><label><input type="radio" name="side" value="sell"><span>Sell</span></label></div><label>Quantity<input type="number" name="quantity" min="0.0001" step="0.0001" placeholder="0.0000" data-quantity required></label><div class="order-summary"><span>Market price <b data-order-price>$445.91</b></span><span>Estimated total <strong data-order-total>$0.00</strong></span><span>Available cash <b>${{ number_format(auth()->user()->cash_balance,2) }}</b></span></div><button class="button wide">Execute order →</button><small>Immediate simulated execution. No securities or crypto are purchased.</small></form></aside>
</div>
<section class="positions-panel glass"><div class="panel-title"><div><span class="eyebrow">PORTFOLIO</span><h2>Open positions</h2></div><span>{{ $positions->count() }} markets</span></div><div class="position-grid">@forelse($positions as $symbol=>$quantity)<article><div class="position-market"><span class="instrument-icon"><img src="https://cdn.simpleicons.org/{{ $iconSlugs[$symbol]??'tesla' }}/ef3f42" alt=""></span><div><b>{{ $symbol }}</b><small>{{ number_format($quantity,4) }} units</small></div></div><strong>${{ number_format($quantity*($quotes[$symbol]??0),2) }}</strong><form method="post" action="{{ route('trade.close',$symbol) }}">@csrf<button class="outline">Close position</button></form></article>@empty<p class="empty">No open positions. Buy a market to begin.</p>@endforelse</div></section>
<section class="orders-panel glass"><div class="panel-title"><div><span class="eyebrow">ACTIVITY</span><h2>Order history</h2></div><span>{{ $trades->total() }} executions</span></div><div class="orders-table"><div class="order-head"><span>Market</span><span>Side</span><span>Quantity</span><span>Execution</span><span>Total</span></div>@forelse($trades as $trade)<div class="order-line"><b>{{ $trade->symbol }}</b><span class="order-side {{ $trade->side }}">{{ strtoupper($trade->side) }}</span><span>{{ $trade->quantity }}</span><span>${{ number_format($trade->price,2) }}</span><strong>${{ number_format($trade->total,2) }}</strong></div>@empty<p class="empty">No trades yet. Select a market to place your first order.</p>@endforelse</div>{{ $trades->links() }}</section>
@endsection
