-- Reference SQLite schema. Laravel migrations are the source of truth.
CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR NOT NULL, email VARCHAR NOT NULL UNIQUE, email_verified_at DATETIME NULL, password VARCHAR NOT NULL, is_admin BOOLEAN NOT NULL DEFAULT 0, cash_balance DECIMAL(16,2) NOT NULL DEFAULT 0, remember_token VARCHAR NULL, created_at DATETIME NULL, updated_at DATETIME NULL);
CREATE TABLE trades (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, symbol VARCHAR(10) NOT NULL, side VARCHAR NOT NULL CHECK(side IN ('buy','sell')), quantity DECIMAL(16,4) NOT NULL, price DECIMAL(16,2) NOT NULL, total DECIMAL(16,2) NOT NULL, executed_at DATETIME NOT NULL, created_at DATETIME NULL, updated_at DATETIME NULL);
CREATE INDEX trades_user_symbol_index ON trades(user_id,symbol);
CREATE TABLE investments (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, plan VARCHAR NOT NULL, principal DECIMAL(16,2) NOT NULL, balance DECIMAL(16,2) NOT NULL, annual_rate DECIMAL(7,4) NOT NULL, status VARCHAR NOT NULL DEFAULT 'active' CHECK(status IN ('active','closed')), started_at DATETIME NOT NULL, last_accrued_at DATETIME NULL, created_at DATETIME NULL, updated_at DATETIME NULL);
CREATE TABLE conversations (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, subject VARCHAR NOT NULL DEFAULT 'Risk discussion', risk_budget DECIMAL(16,2) NULL, status VARCHAR NOT NULL DEFAULT 'automated' CHECK(status IN ('automated','escalated','admin_joined','closed')), assigned_admin_id INTEGER NULL REFERENCES users(id) ON DELETE SET NULL, created_at DATETIME NULL, updated_at DATETIME NULL);
CREATE TABLE messages (id INTEGER PRIMARY KEY AUTOINCREMENT, conversation_id INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE, user_id INTEGER NULL REFERENCES users(id) ON DELETE SET NULL, author_type VARCHAR NOT NULL CHECK(author_type IN ('user','assistant','human_admin')), body TEXT NOT NULL, created_at DATETIME NULL, updated_at DATETIME NULL);
ALTER TABLE users ADD COLUMN kyc_status VARCHAR NOT NULL DEFAULT 'not_started';
ALTER TABLE users ADD COLUMN sanctions_status VARCHAR NOT NULL DEFAULT 'not_screened';
ALTER TABLE users ADD COLUMN locked_at DATETIME NULL;
ALTER TABLE users ADD COLUMN lock_reason VARCHAR NULL;
CREATE TABLE wallet_addresses (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NULL REFERENCES users(id) ON DELETE SET NULL, asset VARCHAR(12) NOT NULL, network VARCHAR(30) NOT NULL, address_encrypted TEXT NOT NULL, address_hash VARCHAR(64) NOT NULL UNIQUE, purpose VARCHAR NOT NULL, is_active BOOLEAN NOT NULL DEFAULT 1, verified_at DATETIME NULL, created_at DATETIME NULL, updated_at DATETIME NULL);
CREATE TABLE funding_requests (id VARCHAR PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, type VARCHAR NOT NULL, asset VARCHAR(12) NOT NULL, network VARCHAR(30) NOT NULL, crypto_amount DECIMAL(28,12) NOT NULL, usd_amount DECIMAL(16,2) NOT NULL, status VARCHAR(40) NOT NULL, wallet_address_id INTEGER NULL REFERENCES wallet_addresses(id) ON DELETE SET NULL, tx_hash VARCHAR(150) NULL, confirmations INTEGER NOT NULL DEFAULT 0, review_note VARCHAR NULL, reviewed_by INTEGER NULL REFERENCES users(id) ON DELETE SET NULL, reviewed_at DATETIME NULL, created_at DATETIME NULL, updated_at DATETIME NULL);
CREATE TABLE compliance_checks (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, funding_request_id VARCHAR NULL REFERENCES funding_requests(id) ON DELETE SET NULL, type VARCHAR NOT NULL, provider VARCHAR NOT NULL, result VARCHAR NOT NULL, risk_score INTEGER NULL, details TEXT NULL, reviewed_by INTEGER NULL REFERENCES users(id) ON DELETE SET NULL, completed_at DATETIME NULL, created_at DATETIME NULL, updated_at DATETIME NULL);
CREATE TABLE ledger_entries (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, funding_request_id VARCHAR NULL REFERENCES funding_requests(id) ON DELETE SET NULL, direction VARCHAR NOT NULL, amount DECIMAL(16,2) NOT NULL, balance_after DECIMAL(16,2) NOT NULL, event VARCHAR NOT NULL, idempotency_key VARCHAR NOT NULL UNIQUE, created_at DATETIME NULL, updated_at DATETIME NULL);
CREATE TABLE audit_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, actor_id INTEGER NULL REFERENCES users(id) ON DELETE SET NULL, event VARCHAR NOT NULL, auditable_type VARCHAR NULL, auditable_id VARCHAR NULL, before TEXT NULL, after TEXT NULL, ip_address VARCHAR(45) NULL, user_agent VARCHAR(500) NULL, created_at DATETIME NULL, updated_at DATETIME NULL);
CREATE TABLE regulatory_licenses (id INTEGER PRIMARY KEY AUTOINCREMENT, jurisdiction VARCHAR NOT NULL, license_type VARCHAR NOT NULL, license_number VARCHAR NULL, status VARCHAR NOT NULL DEFAULT 'planning', effective_at DATE NULL, expires_at DATE NULL, live_operations_allowed BOOLEAN NOT NULL DEFAULT 0, created_at DATETIME NULL, updated_at DATETIME NULL);
CREATE TABLE kyc_profiles (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE, legal_name VARCHAR NOT NULL, date_of_birth DATE NOT NULL, country_code CHAR(2) NOT NULL, document_type VARCHAR NOT NULL, document_path VARCHAR NOT NULL, document_sha256 VARCHAR(64) NOT NULL, created_at DATETIME NULL, updated_at DATETIME NULL);
