<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up():void{
  Schema::table('users',function(Blueprint $t){$t->enum('kyc_status',['not_started','pending','verified','rejected'])->default('not_started')->index();$t->enum('sanctions_status',['not_screened','pending','clear','possible_match','blocked'])->default('not_screened')->index();$t->timestamp('locked_at')->nullable();$t->string('lock_reason')->nullable();});
  Schema::create('wallet_addresses',function(Blueprint $t){$t->id();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('asset',12);$t->string('network',30);$t->text('address_encrypted');$t->string('address_hash',64)->unique();$t->enum('purpose',['deposit','withdrawal']);$t->boolean('is_active')->default(true);$t->timestamp('verified_at')->nullable();$t->timestamps();});
  Schema::create('funding_requests',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->enum('type',['deposit','withdrawal']);$t->string('asset',12);$t->string('network',30);$t->decimal('crypto_amount',28,12);$t->decimal('usd_amount',16,2);$t->string('status',40)->index();$t->foreignId('wallet_address_id')->nullable()->constrained()->nullOnDelete();$t->string('tx_hash',150)->nullable()->index();$t->unsignedInteger('confirmations')->default(0);$t->string('review_note')->nullable();$t->foreignId('reviewed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('reviewed_at')->nullable();$t->timestamps();});
  Schema::create('compliance_checks',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->uuid('funding_request_id')->nullable();$t->string('type');$t->string('provider')->default('sandbox_manual');$t->enum('result',['pending','clear','possible_match','blocked','error']);$t->unsignedInteger('risk_score')->nullable();$t->json('details')->nullable();$t->foreignId('reviewed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('completed_at')->nullable();$t->timestamps();$t->foreign('funding_request_id')->references('id')->on('funding_requests')->nullOnDelete();});
  Schema::create('ledger_entries',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->uuid('funding_request_id')->nullable();$t->enum('direction',['credit','debit']);$t->decimal('amount',16,2);$t->decimal('balance_after',16,2);$t->string('event');$t->string('idempotency_key')->unique();$t->timestamps();$t->foreign('funding_request_id')->references('id')->on('funding_requests')->nullOnDelete();});
  Schema::create('audit_logs',function(Blueprint $t){$t->id();$t->foreignId('actor_id')->nullable()->constrained('users')->nullOnDelete();$t->string('event')->index();$t->string('auditable_type')->nullable();$t->string('auditable_id')->nullable();$t->json('before')->nullable();$t->json('after')->nullable();$t->string('ip_address',45)->nullable();$t->string('user_agent',500)->nullable();$t->timestamps();});
  Schema::create('regulatory_licenses',function(Blueprint $t){$t->id();$t->string('jurisdiction');$t->string('license_type');$t->string('license_number')->nullable();$t->enum('status',['planning','applied','approved','suspended','expired'])->default('planning');$t->date('effective_at')->nullable();$t->date('expires_at')->nullable();$t->boolean('live_operations_allowed')->default(false);$t->timestamps();});
 }
 public function down():void{Schema::dropIfExists('regulatory_licenses');Schema::dropIfExists('audit_logs');Schema::dropIfExists('ledger_entries');Schema::dropIfExists('compliance_checks');Schema::dropIfExists('funding_requests');Schema::dropIfExists('wallet_addresses');Schema::table('users',fn(Blueprint $t)=>$t->dropColumn(['kyc_status','sanctions_status','locked_at','lock_reason']));}
};
