<?php
namespace App\Http\Controllers;
use App\Models\{FundingRequest,Investment,InvestmentPackage,SystemSetting,User,WalletAddress};
use App\Services\{AuditService,ComplianceService,FundingService};
use Illuminate\Http\Request;
class AdminComplianceController extends Controller {
 public function index(){return view('admin.compliance',['funding'=>FundingRequest::with('user','wallet','checks')->latest()->limit(50)->get(),'users'=>User::where('is_admin',false)->latest()->limit(50)->get(),'licenses'=>\App\Models\RegulatoryLicense::all(),'packages'=>InvestmentPackage::catalog(),'wire'=>SystemSetting::wire(),'wallets'=>SystemSetting::cryptoWallets()]);}
 public function user(Request $r,User $user,AuditService $audit){$data=$r->validate(['kyc_status'=>'required|in:not_started,pending,verified,rejected','sanctions_status'=>'required|in:not_screened,pending,clear,possible_match,blocked']);$before=$user->only(['kyc_status','sanctions_status']);$user->update($data);$audit->record('compliance.user_status_changed',$user,$before,$data,$r);return back()->with('status','Compliance status updated and audited.');}
 public function lock(Request $r,User $user,AuditService $audit){$data=$r->validate(['lock_reason'=>'required|string|min:5|max:255']);$user->update(['locked_at'=>now(),'lock_reason'=>$data['lock_reason']]);$audit->record('account.locked',$user,[],['reason'=>$data['lock_reason']],$r);return back()->with('status','Account restricted.');}
 public function unlock(Request $r,User $user,AuditService $audit){$before=$user->only(['locked_at','lock_reason']);$user->update(['locked_at'=>null,'lock_reason'=>null]);$audit->record('account.unlocked',$user,$before,[],$r);return back()->with('status','Account restriction removed.');}
 public function instructions(Request $r,FundingRequest $funding,AuditService $audit){abort_unless($funding->type==='deposit'&&$funding->status==='pending_instructions',422);$data=$r->validate(['address'=>'required|string|max:180']);$wallet=WalletAddress::create(['asset'=>$funding->asset,'network'=>$funding->network,'address_encrypted'=>$data['address'],'address_hash'=>hash('sha256',strtolower(trim($data['address']))),'purpose'=>'deposit','verified_at'=>now()]);$funding->update(['wallet_address_id'=>$wallet->id,'status'=>'awaiting_transfer']);$audit->record('deposit.instructions_assigned',$funding,[],['wallet_id'=>$wallet->id],$r);return back()->with('status','platform deposit instructions assigned.');}
 public function approve(Request $r,FundingRequest $funding,FundingService $service,ComplianceService $compliance,AuditService $audit){$data=$r->validate(['review_note'=>'nullable|string|max:255']);if(!$funding->checks()->exists())$compliance->screenTransaction($funding);if($funding->type==='withdrawal')$funding->wallet?->update(['verified_at'=>now()]);$service->approve($funding,$r->user(),$data['review_note']??'');$audit->record('funding.approved',$funding,[],['status'=>'approved'],$r);return back()->with('status','Deposit or withdrawal confirmed and reconciled.');}
 public function reject(Request $r,FundingRequest $funding,FundingService $service,AuditService $audit){$data=$r->validate(['review_note'=>'required|string|min:5|max:255']);$service->reject($funding,$r->user(),$data['review_note']);$audit->record('funding.rejected',$funding,[],['status'=>'rejected'],$r);return back()->with('status','Funding request rejected.');}
 public function package(Request $r,InvestmentPackage $package,AuditService $audit){$data=$r->validate(['minimum'=>'required|numeric|min:1','maximum'=>'required|numeric|gt:minimum|max:10000000','annual_rate'=>'required|numeric|min:0|max:100','is_active'=>'nullable|boolean']);$before=$package->toArray();$package->update($data+['is_active'=>$r->boolean('is_active')]);Investment::where('plan',$package->slug)->where('status','active')->update(['annual_rate'=>$data['annual_rate']]);$audit->record('investment_package.updated',$package,$before,$package->fresh()->toArray(),$r);return back()->with('status',"{$package->name} settings and active modeled profit rates updated.");}
 public function wire(Request $r,AuditService $audit){$data=$r->validate(['bank_name'=>'required|string|max:120','account_name'=>'required|string|max:120','account_number'=>'required|string|max:60','routing_number'=>'nullable|string|max:60','swift_code'=>'nullable|string|max:30','bank_address'=>'nullable|string|max:255','reference_prefix'=>'required|string|max:12']);$setting=SystemSetting::wire();$before=$setting->value;$setting->update(['value'=>$data,'updated_by'=>$r->user()->id]);$audit->record('wire_instructions.updated',$setting,$before,$data,$r);return back()->with('status','Company wire instructions updated. New sessions receive the revised details.');}
 public function wallets(Request $r,AuditService $audit){$data=$r->validate(['wallets'=>'required|array','wallets.*.network'=>'required|string|max:30','wallets.*.address'=>'required|string|max:180']);$allowed=array_keys(config('funding.wallets'));$submitted=array_keys($data['wallets']);abort_unless(empty(array_diff($submitted,$allowed))&&empty(array_diff($allowed,$submitted)),422);$value=[];foreach($allowed as $asset){$value[$asset]=['network'=>strtolower(trim($data['wallets'][$asset]['network'])),'address'=>trim($data['wallets'][$asset]['address'])];}$setting=SystemSetting::cryptoWallets();$before=$setting->value;$setting->update(['value'=>$value,'updated_by'=>$r->user()->id]);$audit->record('crypto_wallets.updated',$setting,$before,$value,$r);return back()->with('status','Crypto deposit wallets updated. New deposit requests use the revised addresses.');}
}
