<?php
namespace App\Http\Controllers;
use App\Models\{FundingRequest,LedgerEntry,SystemSetting,User,WalletAddress};
use App\Services\{AuditService,ComplianceService,QuoteService};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
class FundingController extends Controller {
 public function index(Request $r,QuoteService $quotes){return view('funding.index',['requests'=>$r->user()->fundingRequests()->with('wallet')->latest()->get(),'wallets'=>config('funding.wallets'),'wire'=>SystemSetting::wire(),'wireExpiresAt'=>now()->addMinutes(20)->timestamp,'rates'=>['BTC'=>$quotes->price('BTC'),'ETH'=>$quotes->price('ETH'),'USDC'=>1,'USDT'=>1]]);}
 public function store(Request $r,ComplianceService $compliance,AuditService $audit){
  $r->mergeIfMissing(['method'=>'crypto']);
  $data=$r->validate(['type'=>'required|in:deposit,withdrawal','method'=>'required|in:crypto,wire','asset'=>'nullable|required_if:method,crypto|in:BTC,ETH,USDC,USDT','network'=>'nullable|required_if:method,crypto|in:bitcoin,ethereum,polygon,trc20','crypto_amount'=>'nullable|required_if:method,crypto|numeric|min:0.00000001','usd_amount'=>'required|numeric|min:10|max:1000000','destination_address'=>'nullable|string|max:500','beneficiary_name'=>'nullable|string|max:120','bank_name'=>'nullable|string|max:120','account_number'=>'nullable|string|max:80','routing_number'=>'nullable|string|max:80','swift_code'=>'nullable|string|max:30','bank_address'=>'nullable|string|max:255']);
  if($data['type']==='withdrawal'&&$data['method']==='crypto'&&blank($data['destination_address']))return back()->withInput()->withErrors(['destination_address'=>'Enter your destination wallet address.']);
  if($data['type']==='withdrawal'&&$data['method']==='wire'){foreach(['beneficiary_name','bank_name','account_number'] as $field)if(blank($data[$field]??null))return back()->withInput()->withErrors([$field=>'Complete the required receiving bank details.']);}
  $compliance->assertFundingEligible($r->user());$wire=SystemSetting::wire();$expected=$data['method']==='crypto'?config("funding.wallets.{$data['asset']}"):null;
  if($data['method']==='crypto'&&(!$expected||$expected['network']!==$data['network']))return back()->withInput()->withErrors(['asset'=>'Choose the network displayed for this asset.']);
  $funding=DB::transaction(function()use($r,$data,$expected,$wire){$user=User::lockForUpdate()->findOrFail($r->user()->id);$wallet=null;$destination=null;
   if($data['method']==='wire'){$asset='USD';$network='wire';$cryptoAmount=$data['usd_amount'];if($data['type']==='withdrawal'){$snapshot=null;$destination=json_encode(['beneficiary_name'=>$data['beneficiary_name'],'bank_name'=>$data['bank_name'],'account_number'=>$data['account_number'],'routing_number'=>$data['routing_number']??null,'swift_code'=>$data['swift_code']??null,'bank_address'=>$data['bank_address']??null],JSON_THROW_ON_ERROR);if((float)$user->cash_balance<(float)$data['usd_amount'])return false;$user->decrement('cash_balance',(float)$data['usd_amount']);$status='awaiting_admin_review';}else{$snapshot=$wire->value;$status='awaiting_transfer';}}
   else{$asset=$data['asset'];$network=$data['network'];$cryptoAmount=$data['crypto_amount'];$snapshot=null;if($data['type']==='deposit'){$hash=hash('sha256',strtolower($expected['address']));$wallet=WalletAddress::firstOrCreate(['address_hash'=>$hash],['asset'=>$asset,'network'=>$network,'address_encrypted'=>$expected['address'],'purpose'=>'deposit','verified_at'=>now()]);$status='awaiting_transfer';}else{$address=trim($data['destination_address']);$hash=hash('sha256',strtolower($address));$existing=WalletAddress::where('address_hash',$hash)->first();if($existing&&$existing->user_id!==$user->id)return null;$wallet=$existing??WalletAddress::create(['address_hash'=>$hash,'user_id'=>$user->id,'asset'=>$asset,'network'=>$network,'address_encrypted'=>$address,'purpose'=>'withdrawal']);if($wallet->asset!==$asset||$wallet->network!==$network)return null;if((float)$user->cash_balance<(float)$data['usd_amount'])return false;$user->decrement('cash_balance',(float)$data['usd_amount']);$status='awaiting_admin_review';}}
   return FundingRequest::create(['user_id'=>$user->id,'type'=>$data['type'],'method'=>$data['method'],'asset'=>$asset,'network'=>$network,'crypto_amount'=>$cryptoAmount,'usd_amount'=>$data['usd_amount'],'status'=>$status,'wallet_address_id'=>$wallet?->id,'wire_details_snapshot'=>$snapshot,'destination_details'=>$destination]);});
  if($funding===null)return back()->withInput()->withErrors(['destination_address'=>'That wallet is already registered to another account or does not match the selected asset and network.']);if($funding===false)return back()->withInput()->withErrors(['usd_amount'=>'Your available BALANCE is $'.number_format($r->user()->cash_balance,2).'.']);if($funding->type==='withdrawal'){$compliance->screenTransaction($funding);LedgerEntry::create(['user_id'=>$r->user()->id,'funding_request_id'=>$funding->id,'direction'=>'debit','amount'=>$funding->usd_amount,'balance_after'=>$r->user()->fresh()->cash_balance,'event'=>'withdrawal_hold','idempotency_key'=>"funding:{$funding->id}:hold"]);} $audit->record('funding.requested',$funding,[],['status'=>$funding->status,'method'=>$funding->method],$r);return back()->with('status',$funding->type==='deposit'?'Deposit ticket created. Submit your transfer reference after sending platform funds.':'Withdrawal submitted for administrator confirmation.');
 }
 public function submitTransaction(Request $r,FundingRequest $funding,ComplianceService $compliance,AuditService $audit){abort_unless($funding->user_id===$r->user()->id,403);abort_unless($funding->type==='deposit'&&$funding->status==='awaiting_transfer',422);$data=$r->validate(['tx_hash'=>'required|string|min:16|max:150']);$funding->update(['tx_hash'=>$data['tx_hash'],'status'=>'under_review']);$compliance->screenTransaction($funding);$audit->record('deposit.transaction_submitted',$funding,[],['tx_hash_suffix'=>substr($data['tx_hash'],-8)],$r);return back()->with('status','Transaction submitted for simulated confirmation and reconciliation.');}
}
