<?php
namespace App\Http\Controllers;
use App\Models\{Trade,User};
use App\Services\QuoteService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
class TradeController extends Controller {
 public function index(Request $r,QuoteService $q){$quotes=$q->symbols();$history=[];foreach(array_keys($quotes) as $symbol)$history[$symbol]=$q->history($symbol,96);$positions=$r->user()->trades()->get()->groupBy('symbol')->map(fn($rows)=>$rows->sum(fn($t)=>($t->side==='buy'?1:-1)*(float)$t->quantity))->filter(fn($qty)=>$qty>0);return view('trade.index',['trades'=>$r->user()->trades()->latest()->paginate(15),'quotes'=>$quotes,'crypto'=>$q->cryptoSymbols(),'histories'=>$history,'positions'=>$positions]);}
 public function store(Request $r,QuoteService $quotes){$data=$r->validate(['symbol'=>'required|string|max:10','side'=>'required|in:buy,sell','quantity'=>'required|numeric|min:0.0001|max:100000']);$symbol=strtoupper($data['symbol']);$price=$quotes->price($symbol);DB::transaction(function()use($r,$data,$symbol,$price){$user=User::lockForUpdate()->findOrFail($r->user()->id);$quantity=(float)$data['quantity'];$total=round($quantity*$price,2);if($data['side']==='buy'){if((float)$user->cash_balance<$total)throw ValidationException::withMessages(['quantity'=>"This order costs $".number_format($total,2).", but your available BALANCE is $".number_format($user->cash_balance,2).'.']);$user->decrement('cash_balance',$total);}else{$owned=(float)Trade::where('user_id',$user->id)->where('symbol',$symbol)->selectRaw("COALESCE(SUM(CASE WHEN side='buy' THEN quantity ELSE -quantity END),0) as qty")->value('qty');if($owned<$quantity)throw ValidationException::withMessages(['quantity'=>"You own ".number_format($owned,4)." {$symbol} shares and cannot sell ".number_format($quantity,4).'.']);$user->increment('cash_balance',$total);}Trade::create(['user_id'=>$user->id,'symbol'=>$symbol,'side'=>$data['side'],'quantity'=>$quantity,'price'=>$price,'total'=>$total,'executed_at'=>now()]);});return back()->with('status','trade executed. No real funds were used.');}
 public function close(Request $r,string $symbol,QuoteService $quotes){$symbol=strtoupper($symbol);$price=$quotes->price($symbol);DB::transaction(function()use($r,$symbol,$price){$user=User::lockForUpdate()->findOrFail($r->user()->id);$quantity=(float)Trade::where('user_id',$user->id)->where('symbol',$symbol)->selectRaw("COALESCE(SUM(CASE WHEN side='buy' THEN quantity ELSE -quantity END),0) as qty")->value('qty');if($quantity<=0)throw ValidationException::withMessages(['position'=>'There is no open position to close.']);$total=round($quantity*$price,2);$user->increment('cash_balance',$total);Trade::create(['user_id'=>$user->id,'symbol'=>$symbol,'side'=>'sell','quantity'=>$quantity,'price'=>$price,'total'=>$total,'executed_at'=>now()]);});return back()->with('status',"{$symbol} position closed at the current simulated reference price.");}
}
